server:
  port: 8080

spring:
  application:
    name: Evaluation-Backend
  profiles:
    active: dev
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
    - org.redisson.spring.starter.RedissonAutoConfigurationV2
  datasource:
    druid:
      initialSize: 5
      minIdle: 5
      maxPoolPreparedStatementPerConnectionSize: 20

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true

eva:
  ldap:
    user-base-dn: ou=member,ou=user
    group-base-dn: ou=member,ou=group
    admin-group-cn: admin

sa-token:
  jwt-secret-key: lagjaohanhlahjiraosujsjstoprjhows
  is-read-cookie: false
#  is-log: true
  token-name: Authorization

ai:
  silicon-api-key: sk-vsmsagfnpmqlbrtqtxnkxdkccydjuytksfyooulmgvjeeilr
  dashscope-api-key: sk-c8041c6ee60d4de68b726495254e92a7




