spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
#          url: jdbc:mariadb://littlestrange.site:40007/evaluate_system?characterEncoding=utf8&serverTimezone=UTC
          # 内网环境
          url: jdbc:mariadb://192.168.1.13:3307/evaluate_system?characterEncoding=utf8&serverTimezone=UTC
          username: root
          password: 30153015
          driver-class-name: org.mariadb.jdbc.Driver
    druid:
      keep-alive: true

  ldap:
    urls: ldap://littlestrange.site:40006
    base: dc=3015,dc=cuit
    username: cn=admin,dc=3015,dc=cuit
    password: 30153015

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


eva:
  config:
    directory: "D:\\Programming\\Java\\Projects\\eva-backend\\data\\config"
  avatar:
#    directory: "/avatar"
    directory: "D:\\Programming\\Java\\Projects\\eva-backend\\data\\avatar"
  records-image:
    directory: "D:\\Programming\\Java\\Projects\\eva-backend\\data\\records"

common:
  print-illegal-arguments: true