server:
  port: 8080

spring:
  application:
    name: Evaluation-Backend
  profiles:
    active: dev
  datasource:
    druid:
      initialSize: 5
      minIdle: 5
      maxPoolPreparedStatementPerConnectionSize: 20

  ldap:
    urls: ldap://littlestrange.site:7086
    base: dc=cuit,dc=edu,dc=cn
    username: cn=eva_system,ou=system,ou=user,dc=cuit,dc=edu,dc=cn
    password: cuit

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true

eva:
  ldap:
    user-base-dn: ou=member,ou=user
    group-base-dn: ou=member,ou=group
    admin-group-cn: admin

sa-token:
  jwt-secret-key: lagjaohanhlahjiraosujsjstoprjhows
