server:
  port: 8080

spring:
  data:
    redis:
      # Redis服务器连接密码（默认为空）
      # password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  application:
    name: Evaluation-Backend
  profiles:
    active: dev
  autoconfigure:
    exclude:
#    - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
    - org.redisson.spring.starter.RedissonAutoConfigurationV2
  datasource:
    druid:
      initialSize: 5
      minIdle: 5
      maxPoolPreparedStatementPerConnectionSize: 20
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 2GB

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true

eva:
  ldap:
    user-base-dn: ou=member,ou=user
    group-base-dn: ou=member,ou=group
    admin-group-cn: admin

sa-token:
  jwt-secret-key: lagjaohanhlahjiraosujsjstoprjhows
  is-read-cookie: false
#  is-log: true
  token-name: Authorization

management:
  endpoints:
    web:
      exposure:
        include: health  # 暴露 health 端点（默认路径 /actuator/health）
  endpoint:
    health:
      show-details: always  # 显示详细健康信息
      probes:
        enabled: true  # 支持 Kubernetes/Swarm 的存活探针
  health:
    livenessState:
      enabled: true  # 启用存活状态检测
    readinessState:
      enabled: true  # 启用就绪状态检测

