spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mariadb://littlestrange.site:3307/evaluate_system?characterEncoding=utf8&serverTimezone=UTC
          username: member
          password: 3015niubi
          driver-class-name: org.mariadb.jdbc.Driver
    druid:
      keep-alive: true