spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
#          url: jdbc:mariadb://littlestrange.site:40005/evaluate_system?characterEncoding=utf8&serverTimezone=UTC
          # 内网环境
          url: jdbc:mariadb://192.168.1.13:3307/evaluate_system?characterEncoding=utf8&serverTimezone=UTC
          username: member
          password: 3015niubi
          driver-class-name: org.mariadb.jdbc.Driver
    druid:
      keep-alive: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eva:
  avatar:
#    directory: "/avatar"
    directory: "D:\\Programming\\Java\\Projects\\eva-backend\\avatar"